package crazytrain

// What are my options for a safe gaming computer?
query "query safe"
    computer:Computer(game == true && risky == false)
end

// Are there any number crunchers that are risky?
query "query risky"
    computer:Computer(crunchNumbers == true && risky == true)
end

// Are all gaming computers hot?
query "query hot"
    computer:Computer(game == true && hot == false)
end

// If a computer has a graphics card and a CPU over 3 GHz, it is loud.
rule "Loud video card"
    salience 1
    no-loop true
    when
        $computer:Computer(videoCard != 0, cpuSpeed > 3)
    then
        $computer.setLoud(true);
        update($computer);
        //System.out.println( $computer.getModelName() + " is loud video card");
end

// If a computer has over 16 GB of memory, it is loud
rule "Loud memory"
    salience 2
    no-loop true
    when
        $computer:Computer(memory > 16)
    then
        $computer.setLoud(true);
        update($computer);
        //System.out.println( $computer.getModelName() + " is loud memory");
end

// If a computer costs less than $1k, it is cheap
rule "Cheapcomputer"
    salience 3
    no-loop true
    when
        $computer:Computer(price < 1000)
    then
        $computer.setCheap(true);
        update($computer);
        //System.out.println( $computer.getModelName() + " is cheap computer");
end

// If a computer costs more than $4k, it is expensive
rule "Expensivecomputer"
    salience 4
    no-loop true
    when
        $computer:Computer(price > 4000)
    then
        $computer.setExpensive(true);
        update($computer);
        //System.out.println( $computer.getModelName() + " is expensive computer");
end

// If a computer has more than 8GB of memory or a CPU faster than 4GHz,it is hot
rule "Hot memory or CPU"
    salience 5
    no-loop true
    when
        $computer:Computer(memory > 8 || cpuSpeed > 4)
    then
        $computer.setHot(true);
        update($computer);
        //System.out.println( $computer.getModelName() + " is hot memory or CPU");
end

// If a computer has a premium graphics card, it can game
// If a computer has a graphics card and a CPU>2GHz, it can game
rule "Can game"
    salience 6
    no-loop true
    when
        $computer:Computer(videoCard == 2 || videoCard != 0 && cpuSpeed > 2)
    then
        $computer.setGame(true);
        update($computer);
        //System.out.println( $computer.getModelName() + " can game");
end

// If a computer has a CPU over 4 GHz and over 4GB memory, it can crunch numbers
// If a computer has a premium graphics card, it can crunch numbers
rule "Can crunch numbers"
    salience 7
    no-loop true
    when
        $computer:Computer(cpuSpeed > 4 && memory > 4 || videoCard == 2)
    then
        $computer.setCrunchNumbers(true);
        update($computer);
        //System.out.println( $computer.getModelName() + " can crunch numbers");
end

// If a computer is cheap and hot, it is risky.
rule "Risky computer"
    salience 8
    no-loop true
    when
        $computer:Computer(hot == true && cheap == true)
    then
        $computer.setRisky(true);
        update($computer);
        //System.out.println( $computer.getModelName() + " is risky computer");
end